name: Deployment

on:
  push:
    branches: [main]

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    timeout-minutes: 30

    env:
      DATABASE_URL: ${{ secrets.DATABASE_URL }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up go
        uses: actions/setup-go@v5
        with:
          go-version: "1.23.0"

      - name: Set up goose
        run: go install github.com/pressly/goose/v3/cmd/goose@latest

      - name: Build app
        run: ./scripts/buildprod.sh

      - id: 'auth'
        uses: 'google-github-actions/auth@v2'
        with:
          credentials_json: '${{ secrets.GCP_CREDENTIALS }}'

      - name: 'Set up Cloud SDK'
        uses: 'google-github-actions/setup-gcloud@v2'

      - name: 'Use gcloud CLI'
        run: 'gcloud info'

      - name: Build docker image
        run: gcloud builds submit --tag southamerica-east1-docker.pkg.dev/notely-466208/notely-ar-repo/notely:latest .

      - name: Auto migration with goose
        run: ./scripts/migrateup.sh

      - name: Deploy to Cloud Run
        run: gcloud run deploy notely --image southamerica-east1-docker.pkg.dev/notely-466208/notely-ar-repo/notely:latest --region us-central1 --allow-unauthenticated --project notely-466208 --max-instances=4
