name: Deployment

on:
  push:
    branches: [main]

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    timeout-minutes: 30

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up go
        uses: actions/setup-go@v5
        with:
          go-version: "1.23.0"

      - name: Build app
        run: ./scripts/buildprod.sh

